import type { Business, User } from "./types";
import { nowIso } from "./utils";

export const DEMO_USER: User = {
  id: "user_demo",
  email: "demo@loca.app",
  name: "Usuaria Demo",
  isDemo: true,
  createdAt: nowIso(),
};

export const DEMO_BUSINESSES: Business[] = [
  {
    id: "biz_cafe_bruma",
    userId: "user_demo",
    name: "Café Bruma",
    industry: "Food & Beverage",
    subcategory: "Café",
    businessType: "Local físico",
    businessModel: "B2C",
    yearFounded: "2021",
    employees: "1-10",
    country: "Argentina",
    state: "CABA",
    city: "Buenos Aires",
    shortDescription:
      "Café de especialidad de barrio con granos de origen y pastelería casera.",
    fullDescription:
      "Café Bruma es un espacio cálido de café de especialidad en el corazón del barrio. Trabajamos con productores locales, tostamos en pequeñas tandas y acompañamos con pastelería casera. Buscamos que cada visita se sienta como un ritual.",
    values: ["Calidad", "Comunidad", "Autenticidad", "Apoyo local"],
    competitiveAdvantages: ["Mayor calidad", "Producción local", "Atención personalizada"],
    marketingChannels: ["Instagram", "TikTok", "Facebook", "WhatsApp"],
    marketingStrategy:
      "Posteamos esporádicamente fotos de productos, sin un plan claro ni constancia.",
    marketingActivities: ["Redes orgánicas", "Recomendaciones boca a boca"],
    hasSeasonality: true,
    seasonality: "Más flujo en otoño/invierno; bajan ventas en vacaciones de verano.",
    seasonalityTags: ["Otoño", "Invierno"],
    hasSpecialDates: true,
    specialDates: ["Día del Café (1 de octubre)", "Navidad", "Día de la Madre"],
    hasWebsite: false,
    websiteUrl: "",
    websiteExtractionStatus: "idle",
    brandColors: ["#ec4899", "#84cc16", "#18181b"],
    productsServices: [
      {
        id: "ps_cafe_filtrado",
        type: "producto",
        name: "Café filtrado de origen",
        category: "Bebidas",
        subcategory: "Café",
        shortDescription: "Métodos V60 y Chemex con granos de single origin.",
        longDescription:
          "Selección rotativa de granos de origen, preparados en métodos de filtrado para resaltar notas únicas de cada cosecha.",
        features: ["Single origin", "Tueste propio", "Rotación mensual"],
        variants: ["V60", "Chemex", "Aeropress"],
        pricingType: "rango",
        currency: "ARS",
        priceMin: 2500,
        priceMax: 3800,
        imageCaption: "Taza de café filtrado sobre mesa de madera con luz natural.",
        keywords: ["café de especialidad", "filtrado", "single origin"],
        negativeKeywords: ["instantáneo"],
        isTopSeller: true,
      },
      {
        id: "ps_medialunas",
        type: "producto",
        name: "Medialunas caseras",
        category: "Pastelería",
        subcategory: "Facturas",
        shortDescription: "Hechas cada mañana con manteca de verdad.",
        longDescription: "Pastelería artesanal horneada en el día.",
        features: ["Receta artesanal", "Horneado diario"],
        variants: ["Dulce", "Salada"],
        pricingType: "fijo",
        currency: "ARS",
        priceMin: 900,
        keywords: ["medialunas", "pastelería", "desayuno"],
        negativeKeywords: [],
        isTopSeller: false,
      },
    ],
    audience: {
      ageRanges: ["18-24", "25-34", "35-44"],
      gender: "todos",
      locationLogic: "ciudad",
      locations: ["Buenos Aires"],
      socioeconomicLevel: "medio_alto",
      painPoints: [
        "No encuentran café de calidad cerca",
        "Buscan un lugar tranquilo para trabajar o charlar",
      ],
      behavior: "Activos en Instagram, valoran la estética y las recomendaciones.",
      segments: ["Profesionales jóvenes", "Estudiantes", "Amantes del café"],
    },
    goals: {
      primaryContentGoal: "ventas",
      salesGoalType: "visita_local",
      businessObjectives: "Llenar el local en horarios valle y fidelizar clientes.",
      successMetrics: ["Visitas al local", "Clientes recurrentes", "Alcance local"],
      marketingObjectives: "Crecer la comunidad local y aumentar visitas entre semana.",
      timeline: "Próximos 3 meses",
    },
    onboardingComplete: true,
    isDemo: true,
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },
  {
    id: "biz_casa_nativa",
    userId: "user_demo",
    name: "Casa Nativa",
    industry: "E-commerce / Online Stores",
    subcategory: "Handmade goods store",
    businessType: "Online",
    businessModel: "B2C",
    yearFounded: "2020",
    employees: "1-10",
    country: "Argentina",
    state: "Córdoba",
    city: "Córdoba",
    shortDescription:
      "Tienda online de objetos de diseño hechos a mano por artesanos locales.",
    fullDescription:
      "Casa Nativa es una tienda online que reúne objetos de decoración y uso diario hechos a mano por artesanos de toda la región. Cada pieza es única, sustentable y con historia. Enviamos a todo el país.",
    values: ["Hecho a mano / artesanal", "Sustentabilidad", "Apoyo local", "Autenticidad"],
    competitiveAdvantages: [
      "Productos exclusivos",
      "Materiales sustentables",
      "Producción local",
    ],
    marketingChannels: ["Instagram", "Facebook", "TikTok", "Pinterest"],
    marketingStrategy:
      "Vendemos por Instagram y web, pero sin contenido planificado ni campañas.",
    marketingActivities: ["Redes orgánicas", "Publicidad paga / Ads"],
    hasSeasonality: true,
    seasonality: "Picos en Día de la Madre, Navidad y Hot Sale.",
    seasonalityTags: ["Día de la Madre", "Navidad", "Hot Sale / Cyber Monday"],
    hasSpecialDates: true,
    specialDates: ["Día de la Madre", "Navidad", "Hot Sale", "Cyber Monday"],
    hasWebsite: true,
    websiteUrl: "https://casanativa.example",
    websiteExtractionStatus: "idle",
    brandColors: ["#ec4899", "#84cc16", "#ffffff"],
    productsServices: [
      {
        id: "ps_macetas",
        type: "producto",
        name: "Macetas de cerámica artesanal",
        category: "Decoración",
        subcategory: "Cerámica",
        shortDescription: "Piezas únicas torneadas a mano y esmaltadas.",
        longDescription:
          "Macetas de cerámica hechas a mano por ceramistas locales. Cada pieza es irrepetible.",
        features: ["Hecho a mano", "Esmalte sin plomo", "Pieza única"],
        variants: ["Chica", "Mediana", "Grande"],
        pricingType: "por_variante",
        currency: "ARS",
        priceMin: 6000,
        priceMax: 14000,
        imageCaption: "Maceta de cerámica con planta sobre fondo neutro.",
        keywords: ["cerámica", "macetas", "decoración artesanal", "hecho a mano"],
        negativeKeywords: ["plástico", "industrial"],
        isTopSeller: true,
      },
      {
        id: "ps_textiles",
        type: "producto",
        name: "Textiles tejidos en telar",
        category: "Hogar",
        subcategory: "Textiles",
        shortDescription: "Caminos de mesa y almohadones tejidos en telar.",
        longDescription: "Textiles de lana natural teñidos con tintes vegetales.",
        features: ["Lana natural", "Tintes vegetales", "Telar manual"],
        variants: ["Camino de mesa", "Almohadón", "Manta"],
        pricingType: "rango",
        currency: "ARS",
        priceMin: 8000,
        priceMax: 25000,
        keywords: ["telar", "textiles", "lana", "decoración"],
        negativeKeywords: ["sintético"],
        isTopSeller: false,
      },
    ],
    audience: {
      ageRanges: ["25-34", "35-44", "45-54"],
      gender: "femenino",
      locationLogic: "pais",
      locations: ["Argentina"],
      socioeconomicLevel: "medio_alto",
      painPoints: [
        "Quieren decorar con piezas con identidad, no de cadenas",
        "Buscan productos sustentables y con historia",
      ],
      behavior: "Compran online, se inspiran en Instagram y Pinterest.",
      segments: ["Amantes de la decoración", "Consumo consciente", "Regalos especiales"],
    },
    goals: {
      primaryContentGoal: "ventas",
      salesGoalType: "compra_ecommerce",
      businessObjectives: "Aumentar ventas online y ticket promedio.",
      successMetrics: ["Ventas web", "Tasa de conversión", "Alcance"],
      marketingObjectives: "Construir marca y vender de forma constante todo el año.",
      timeline: "Próximos 6 meses",
    },
    onboardingComplete: true,
    isDemo: true,
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },
];
