import type { Business, User } from "./types";
import { nowIso } from "./utils";

// ── Paletas por perfil ───────────────────────────────────────
const CAFE_BRAND_KIT = {
  colors: {
    primary: "#b45309",
    palette: [
      { name: "Caramelo", hex: "#b45309", role: "primary" as const, source: "user" as const, confidence: "high" as const },
      { name: "Verde oliva", hex: "#65a30d", role: "accent" as const, source: "user" as const, confidence: "high" as const },
    ],
  },
  typography: { heading: { family: "Poppins", source: "user" as const, confidence: "high" as const }, body: { family: "Inter", source: "user" as const, confidence: "high" as const } },
  logos: [],
  visualStyle: { mood: ["Cálido", "Artesanal"], imageStyle: "Fotos cálidas de producto y ambiente, luz natural." },
  voiceTone: { toneTags: ["Cercano", "Auténtico", "Cálido"] },
  brandKeywords: [],
  avoidList: [],
};

const PSI_BRAND_KIT = {
  colors: {
    primary: "#0f766e",
    palette: [
      { name: "Verde calma", hex: "#0f766e", role: "primary" as const, source: "user" as const, confidence: "high" as const },
      { name: "Arena", hex: "#e7e5e4", role: "background" as const, source: "user" as const, confidence: "high" as const },
    ],
  },
  typography: { heading: { family: "Lora", source: "user" as const, confidence: "high" as const }, body: { family: "Inter", source: "user" as const, confidence: "high" as const } },
  logos: [],
  visualStyle: { mood: ["Sereno", "Cercano", "Confiable"], imageStyle: "Imágenes serenas, luz suave, tonos calmos." },
  voiceTone: { toneTags: ["Cálido", "Respetuoso", "Claro"], formality: "neutral" as const },
  brandKeywords: [],
  avoidList: ["No prometer curas ni resultados garantizados", "No dar diagnósticos por redes"],
};

const SAAS_BRAND_KIT = {
  colors: {
    primary: "#4f46e5",
    palette: [
      { name: "Índigo", hex: "#4f46e5", role: "primary" as const, source: "user" as const, confidence: "high" as const },
      { name: "Cian", hex: "#06b6d4", role: "accent" as const, source: "user" as const, confidence: "high" as const },
    ],
  },
  typography: { heading: { family: "Inter", source: "user" as const, confidence: "high" as const }, body: { family: "Inter", source: "user" as const, confidence: "high" as const } },
  logos: [],
  visualStyle: { mood: ["Tecnológico", "Moderno", "Minimalista"], imageStyle: "Estética tech, UI limpia, gradientes sutiles." },
  voiceTone: { toneTags: ["Directo", "Profesional", "Claro"], formality: "neutral" as const },
  brandKeywords: [],
  avoidList: ["No usar jerga técnica innecesaria"],
};

export const DEMO_USER: User = {
  id: "user_demo",
  email: "demo@loca.app",
  name: "Usuaria Demo",
  isDemo: true,
  createdAt: nowIso(),
};

// Metadata para la pantalla de selección de demo.
export interface DemoProfile {
  id: string;
  label: string;
  tagline: string;
  emoji: string;
}

export const DEMO_PROFILES: DemoProfile[] = [
  { id: "biz_cafe_bruma", label: "Café de especialidad", tagline: "Un comercio local: Café Bruma", emoji: "☕" },
  { id: "biz_psi_lucia", label: "Profesional independiente", tagline: "Lucía Fernández, psicóloga", emoji: "🧠" },
  { id: "biz_saas_nodo", label: "Startup SaaS", tagline: "Nodo, software B2B", emoji: "🚀" },
];

export const DEMO_BUSINESSES: Business[] = [
  // ── Pequeño comercio: café de especialidad ──
  {
    id: "biz_cafe_bruma",
    userId: "user_demo",
    name: "Café Bruma",
    industry: "Food & Beverage",
    subcategory: "Café",
    businessType: "Local físico",
    businessStage: "pyme",
    businessModel: "B2C",
    yearFounded: "2021",
    employees: "1-10",
    country: "Argentina",
    state: "CABA",
    city: "Buenos Aires",
    shortDescription: "Café de especialidad de barrio con granos de origen y pastelería casera.",
    fullDescription:
      "Café Bruma es un espacio cálido de café de especialidad en el corazón del barrio. Trabajamos con productores locales, tostamos en pequeñas tandas y acompañamos con pastelería casera. Buscamos que cada visita se sienta como un ritual.",
    values: ["Calidad", "Comunidad", "Autenticidad", "Apoyo local"],
    competitiveAdvantages: ["Mayor calidad", "Producción local", "Atención personalizada"],
    marketingChannels: ["Instagram", "TikTok", "Facebook", "WhatsApp"],
    marketingStrategy: "Posteamos esporádicamente fotos de productos, sin un plan claro ni constancia.",
    marketingActivities: ["Redes orgánicas", "Recomendaciones boca a boca"],
    hasSeasonality: true,
    seasonality: "Más flujo en otoño/invierno; bajan ventas en vacaciones de verano.",
    seasonalityTags: ["Otoño", "Invierno"],
    hasSpecialDates: true,
    specialDates: ["Día del Café (1 de octubre)", "Navidad", "Día de la Madre"],
    hasWebsite: false,
    websiteUrl: "",
    websiteExtractionStatus: "idle",
    brandColors: ["#b45309", "#65a30d", "#18181b"],
    brandKit: CAFE_BRAND_KIT,
    productsServices: [
      {
        id: "ps_cafe_filtrado",
        type: "producto",
        name: "Café filtrado de origen",
        category: "Bebidas",
        subcategory: "Café",
        shortDescription: "Métodos V60 y Chemex con granos de single origin.",
        longDescription:
          "Selección rotativa de granos de origen, preparados en métodos de filtrado para resaltar notas únicas de cada cosecha.",
        features: ["Single origin", "Tueste propio", "Rotación mensual"],
        variants: ["V60", "Chemex", "Aeropress"],
        pricingType: "rango",
        currency: "ARS",
        priceMin: 2500,
        priceMax: 3800,
        imageCaption: "Taza de café filtrado sobre mesa de madera con luz natural.",
        keywords: ["café de especialidad", "filtrado", "single origin"],
        negativeKeywords: ["instantáneo"],
        isTopSeller: true,
      },
      {
        id: "ps_medialunas",
        type: "producto",
        name: "Medialunas caseras",
        category: "Pastelería",
        subcategory: "Facturas",
        shortDescription: "Hechas cada mañana con manteca de verdad.",
        longDescription: "Pastelería artesanal horneada en el día.",
        features: ["Receta artesanal", "Horneado diario"],
        variants: ["Dulce", "Salada"],
        pricingType: "fijo",
        currency: "ARS",
        priceMin: 900,
        keywords: ["medialunas", "pastelería", "desayuno"],
        negativeKeywords: [],
        isTopSeller: false,
      },
    ],
    audience: {
      ageRanges: ["18-24", "25-34", "35-44"],
      gender: "todos",
      locationLogic: "ciudad",
      locations: ["Buenos Aires"],
      socioeconomicLevel: "medio_alto",
      painPoints: ["No encuentran café de calidad cerca", "Buscan un lugar tranquilo para trabajar o charlar"],
      behavior: "Activos en Instagram, valoran la estética y las recomendaciones.",
      segments: ["Profesionales jóvenes", "Estudiantes", "Amantes del café"],
    },
    goals: {
      primaryContentGoal: "ventas",
      salesGoalType: "visita_local",
      businessObjectives: "Llenar el local en horarios valle y fidelizar clientes.",
      successMetrics: ["Visitas al local", "Clientes recurrentes", "Alcance local"],
      marketingObjectives: "Crecer la comunidad local y aumentar visitas entre semana.",
      timeline: "Próximos 3 meses",
    },
    onboardingComplete: true,
    isDemo: true,
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },

  // ── Profesional independiente: psicóloga ──
  {
    id: "biz_psi_lucia",
    userId: "user_demo",
    name: "Lucía Fernández · Psicóloga",
    industry: "Health & Wellness",
    subcategory: "Salud mental",
    businessType: "Marca personal",
    businessStage: "profesional_independiente",
    businessModel: "B2C",
    yearFounded: "2018",
    employees: "Solo yo",
    country: "Argentina",
    state: "CABA",
    city: "Buenos Aires",
    shortDescription: "Psicóloga clínica. Terapia individual y de pareja, presencial y online.",
    fullDescription:
      "Soy Lucía, psicóloga clínica con enfoque cognitivo-conductual. Acompaño a adultos y parejas a atravesar ansiedad, estrés y momentos de cambio, con un espacio cálido y sin juicios. Atiendo en consultorio y online para toda Argentina.",
    values: ["Empatía", "Confidencialidad", "Rigor profesional", "Cercanía"],
    competitiveAdvantages: ["Trato cercano y humano", "Enfoque basado en evidencia", "Atención online flexible"],
    marketingChannels: ["Instagram", "LinkedIn"],
    marketingStrategy: "Publico algún tip suelto en Instagram, sin constancia ni estrategia.",
    marketingActivities: ["Redes orgánicas", "Recomendaciones de pacientes"],
    hasSeasonality: true,
    seasonality: "Más consultas al inicio del año y post-vacaciones.",
    seasonalityTags: ["Inicio de año", "Marzo"],
    hasSpecialDates: true,
    specialDates: ["Día de la Salud Mental (10 de octubre)"],
    hasWebsite: false,
    websiteUrl: "",
    websiteExtractionStatus: "idle",
    brandColors: ["#0f766e", "#e7e5e4", "#1c1917"],
    brandKit: PSI_BRAND_KIT,
    productsServices: [
      {
        id: "ps_sesion_individual",
        type: "servicio",
        name: "Terapia individual",
        category: "Sesiones",
        shortDescription: "Sesiones semanales de 50 minutos, presencial u online.",
        longDescription: "Espacio de terapia individual para trabajar ansiedad, estrés, autoestima y procesos de cambio.",
        features: ["50 minutos", "Presencial u online", "Enfoque cognitivo-conductual"],
        variants: ["Presencial", "Online"],
        pricingType: "fijo",
        currency: "ARS",
        priceMin: 18000,
        keywords: ["terapia", "psicóloga", "ansiedad", "salud mental"],
        negativeKeywords: [],
        isTopSeller: true,
      },
      {
        id: "ps_terapia_pareja",
        type: "servicio",
        name: "Terapia de pareja",
        category: "Sesiones",
        shortDescription: "Acompañamiento para mejorar la comunicación y los vínculos.",
        longDescription: "Sesiones para parejas que quieren trabajar la comunicación, los conflictos y reconectar.",
        features: ["60 minutos", "Presencial u online"],
        variants: [],
        pricingType: "fijo",
        currency: "ARS",
        priceMin: 25000,
        keywords: ["terapia de pareja", "vínculos"],
        negativeKeywords: [],
        isTopSeller: false,
      },
      {
        id: "ps_primera_consulta",
        type: "servicio",
        name: "Primera consulta",
        category: "Sesiones",
        shortDescription: "Una primera entrevista para conocernos y ver cómo trabajar.",
        longDescription: "Entrevista inicial sin compromiso para entender tu situación y proponer un plan.",
        features: ["Sin compromiso"],
        variants: [],
        pricingType: "fijo",
        currency: "ARS",
        priceMin: 12000,
        keywords: ["primera consulta", "psicología"],
        negativeKeywords: [],
        isTopSeller: false,
      },
    ],
    audience: {
      ageRanges: ["25-34", "35-44", "45-54"],
      gender: "todos",
      locationLogic: "pais",
      locations: ["Argentina"],
      socioeconomicLevel: "medio_alto",
      painPoints: [
        "Sienten ansiedad o estrés y no saben por dónde empezar",
        "Buscan un profesional de confianza y cercano",
        "Prefieren la comodidad de la atención online",
      ],
      behavior: "Buscan referentes en Instagram, valoran contenido claro y humano.",
      segments: ["Adultos con ansiedad", "Parejas en conflicto", "Personas en momentos de cambio"],
    },
    goals: {
      primaryContentGoal: "confianza",
      businessObjectives: "Conseguir consultas de pacientes ideales y llenar la agenda.",
      successMetrics: ["Consultas nuevas", "Mensajes por DM", "Alcance"],
      marketingObjectives: "Construir autoridad y cercanía para que lleguen consultas por redes.",
      timeline: "Próximos 3 meses",
    },
    onboardingComplete: true,
    isDemo: true,
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },

  // ── Startup SaaS ──
  {
    id: "biz_saas_nodo",
    userId: "user_demo",
    name: "Nodo",
    industry: "Tech & Software Startups",
    subcategory: "SaaS B2B",
    businessType: "Online",
    businessStage: "startup",
    businessModel: "B2B",
    yearFounded: "2023",
    employees: "11-50",
    country: "Argentina",
    state: "CABA",
    city: "Buenos Aires",
    shortDescription: "Software que automatiza la gestión de pedidos para pymes de logística.",
    fullDescription:
      "Nodo es una plataforma SaaS que centraliza y automatiza la gestión de pedidos y entregas para pymes de logística. Reemplaza planillas y WhatsApp por un panel simple, con seguimiento en tiempo real e integraciones. Ayudamos a los equipos a hacer más con menos.",
    values: ["Simplicidad", "Eficiencia", "Confiabilidad", "Cercanía con el cliente"],
    competitiveAdvantages: ["Implementación en días, no meses", "Precio accesible para pymes", "Soporte humano en español"],
    marketingChannels: ["LinkedIn", "Instagram"],
    marketingStrategy: "El equipo fundador postea a veces en LinkedIn, sin un plan de contenido.",
    marketingActivities: ["Redes orgánicas", "Email marketing", "Publicidad paga / Ads"],
    hasSeasonality: false,
    seasonality: "",
    seasonalityTags: [],
    hasSpecialDates: false,
    specialDates: [],
    hasWebsite: true,
    websiteUrl: "https://nodo.example",
    websiteExtractionStatus: "idle",
    brandColors: ["#4f46e5", "#06b6d4", "#0b1120"],
    brandKit: SAAS_BRAND_KIT,
    productsServices: [
      {
        id: "ps_plan_pro",
        type: "servicio",
        name: "Nodo Pro",
        category: "Suscripción",
        shortDescription: "Panel completo de gestión de pedidos con seguimiento en tiempo real.",
        longDescription:
          "Suscripción mensual que incluye panel de pedidos, seguimiento de entregas en tiempo real, reportes e integraciones con tu ecommerce.",
        features: ["Seguimiento en tiempo real", "Reportes automáticos", "Integraciones", "Soporte en español"],
        variants: ["Mensual", "Anual"],
        pricingType: "fijo",
        currency: "USD",
        priceMin: 49,
        keywords: ["software logística", "gestión de pedidos", "saas pymes"],
        negativeKeywords: [],
        isTopSeller: true,
      },
      {
        id: "ps_onboarding",
        type: "servicio",
        name: "Implementación guiada",
        category: "Servicios",
        shortDescription: "Te configuramos todo y capacitamos a tu equipo en pocos días.",
        longDescription: "Servicio de onboarding donde migramos tus datos y dejamos a tu equipo listo para usar Nodo.",
        features: ["Migración de datos", "Capacitación del equipo"],
        variants: [],
        pricingType: "fijo",
        currency: "USD",
        priceMin: 0,
        keywords: ["onboarding", "implementación"],
        negativeKeywords: [],
        isTopSeller: false,
      },
    ],
    audience: {
      ageRanges: ["25-34", "35-44", "45-54"],
      gender: "todos",
      locationLogic: "regional",
      locations: ["Argentina", "México", "Chile"],
      socioeconomicLevel: "medio_alto",
      painPoints: [
        "Gestionan pedidos con planillas y WhatsApp y se les escapan cosas",
        "No tienen visibilidad de las entregas en tiempo real",
        "El software tradicional es caro y complejo de implementar",
      ],
      behavior: "Decisores que investigan en LinkedIn y comparan herramientas antes de comprar.",
      segments: ["Dueños de pymes de logística", "Jefes de operaciones", "Ecommerce en crecimiento"],
    },
    goals: {
      primaryContentGoal: "visibilidad",
      salesGoalType: "lead_magnet",
      businessObjectives: "Generar leads calificados y demos agendadas.",
      successMetrics: ["Demos agendadas", "Leads calificados", "Alcance en LinkedIn"],
      marketingObjectives: "Posicionar a Nodo como la opción simple y accesible para pymes de logística.",
      timeline: "Próximos 6 meses",
    },
    onboardingComplete: true,
    isDemo: true,
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },
];
