// ─────────────────────────────────────────────────────────────
// Datos geográficos normalizados para los selects searchable.
// LATAM primero (priorizado para el público de LOCA).
// ─────────────────────────────────────────────────────────────

// Países priorizados arriba + resto del mundo más común.
export const COUNTRIES: string[] = [
  // LATAM + España + EEUU priorizados
  "Argentina",
  "México",
  "Colombia",
  "Chile",
  "Perú",
  "Uruguay",
  "Paraguay",
  "Bolivia",
  "Ecuador",
  "Brasil",
  "España",
  "Estados Unidos",
  // Resto frecuente
  "Venezuela",
  "Guatemala",
  "Costa Rica",
  "Panamá",
  "República Dominicana",
  "Honduras",
  "El Salvador",
  "Nicaragua",
  "Puerto Rico",
  "Cuba",
  "Canadá",
  "Reino Unido",
  "Francia",
  "Italia",
  "Alemania",
  "Portugal",
  "Otro",
];

// Provincias / estados conocidos. Si el país no está, el select permite escribir.
export const REGIONS_BY_COUNTRY: Record<string, string[]> = {
  Argentina: [
    "CABA (Ciudad de Buenos Aires)",
    "Buenos Aires",
    "Catamarca",
    "Chaco",
    "Chubut",
    "Córdoba",
    "Corrientes",
    "Entre Ríos",
    "Formosa",
    "Jujuy",
    "La Pampa",
    "La Rioja",
    "Mendoza",
    "Misiones",
    "Neuquén",
    "Río Negro",
    "Salta",
    "San Juan",
    "San Luis",
    "Santa Cruz",
    "Santa Fe",
    "Santiago del Estero",
    "Tierra del Fuego",
    "Tucumán",
  ],
  México: [
    "Ciudad de México",
    "Jalisco",
    "Nuevo León",
    "Estado de México",
    "Puebla",
    "Guanajuato",
    "Veracruz",
    "Querétaro",
    "Yucatán",
    "Baja California",
    "Chihuahua",
    "Sonora",
    "Quintana Roo",
    "Michoacán",
    "Coahuila",
    "Sinaloa",
    "Oaxaca",
    "Chiapas",
  ],
  Colombia: [
    "Bogotá D.C.",
    "Antioquia",
    "Valle del Cauca",
    "Atlántico",
    "Santander",
    "Cundinamarca",
    "Bolívar",
  ],
  Chile: [
    "Región Metropolitana",
    "Valparaíso",
    "Biobío",
    "Maule",
    "Araucanía",
    "Antofagasta",
    "Los Lagos",
  ],
  Perú: ["Lima", "Arequipa", "La Libertad", "Piura", "Cusco", "Lambayeque"],
  Uruguay: ["Montevideo", "Canelones", "Maldonado", "Colonia", "Salto"],
  España: [
    "Madrid",
    "Cataluña",
    "Andalucía",
    "Comunidad Valenciana",
    "País Vasco",
    "Galicia",
  ],
  "Estados Unidos": [
    "California",
    "Texas",
    "Florida",
    "New York",
    "Illinois",
    "Arizona",
    "New Jersey",
  ],
};

export function regionsFor(country: string): string[] {
  return REGIONS_BY_COUNTRY[country] || [];
}
