-- ─────────────────────────────────────────────────────────────
-- LOCA MVP — migración 0004: catálogo de fechas especiales/temporadas
-- Ejecutar en: Supabase Dashboard → SQL Editor → New query
--
-- Catálogo de referencia (NO user-scoped): sugerencias de "temporadas
-- fuertes" y "fechas especiales" por industria, mostradas en el
-- onboarding. industry = '__default__' es el fallback genérico cuando
-- la industria del negocio no tiene curación propia.
-- ─────────────────────────────────────────────────────────────

create table public.special_dates_catalog (
  id bigint generated always as identity primary key,
  industry text not null,
  kind text not null check (kind in ('seasonality', 'special_date')),
  label text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create index special_dates_catalog_industry_kind_idx
  on public.special_dates_catalog (industry, kind, sort_order);

-- RLS habilitado SIN policies: el cliente (anon key) no puede leer ni
-- escribir esta tabla. Se sirve al frontend a través de una ruta API
-- server-side (service role) — mismo criterio que meta_connections.
alter table public.special_dates_catalog enable row level security;

insert into public.special_dates_catalog (industry, kind, label, sort_order) values
  ('__default__', 'seasonality', '☀️ Verano', 0),
  ('__default__', 'seasonality', '❄️ Invierno', 1),
  ('__default__', 'seasonality', '🌸 Primavera', 2),
  ('__default__', 'seasonality', '🍂 Otoño', 3),
  ('__default__', 'seasonality', '🎒 Vuelta a clases', 4),
  ('__default__', 'seasonality', '👩 Día de la Madre', 5),
  ('__default__', 'seasonality', '👨 Día del Padre', 6),
  ('__default__', 'seasonality', '🎄 Navidad', 7),
  ('__default__', 'seasonality', '🎆 Año Nuevo', 8),
  ('__default__', 'seasonality', '🛍️ Hot Sale / Cyber Monday', 9),
  ('__default__', 'seasonality', '🏖️ Vacaciones', 10),
  ('__default__', 'seasonality', '✈️ Fechas turísticas', 11),
  ('__default__', 'seasonality', 'Otra', 12),
  ('__default__', 'special_date', '🎂 Aniversario de la marca', 0),
  ('__default__', 'special_date', '🚀 Lanzamientos', 1),
  ('__default__', 'special_date', '🏷️ Fechas comerciales', 2),
  ('__default__', 'special_date', '🎪 Eventos propios', 3),
  ('__default__', 'special_date', '💸 Temporadas de descuentos', 4),
  ('__default__', 'special_date', '🏢 Ferias / exposiciones', 5),
  ('__default__', 'special_date', '🇦🇷 Fechas patrias', 6),
  ('__default__', 'special_date', 'Otra', 7),
  ('Food & Beverage', 'seasonality', '☀️ Verano', 0),
  ('Food & Beverage', 'seasonality', '❄️ Invierno', 1),
  ('Food & Beverage', 'seasonality', '🎄 Navidad y Fin de Año', 2),
  ('Food & Beverage', 'seasonality', '🎒 Vuelta a clases', 3),
  ('Beauty & Personal Care', 'seasonality', '👩 Día de la Madre', 0),
  ('Beauty & Personal Care', 'seasonality', '🎄 Navidad y Fin de Año', 1),
  ('Beauty & Personal Care', 'seasonality', '💒 Temporada de casamientos', 2),
  ('Health & Wellness', 'seasonality', '🎯 Enero (propósitos de año nuevo)', 0),
  ('Health & Wellness', 'seasonality', '☀️ Verano', 1),
  ('Health & Wellness', 'seasonality', '❄️ Invierno', 2),
  ('Sports & Fitness', 'seasonality', '🎯 Enero (propósitos de año nuevo)', 0),
  ('Sports & Fitness', 'seasonality', '☀️ Operación verano', 1),
  ('Sports & Fitness', 'seasonality', '❄️ Invierno', 2),
  ('Retail & Local Stores', 'seasonality', '🎄 Navidad y Fin de Año', 0),
  ('Retail & Local Stores', 'seasonality', '🎒 Vuelta a clases', 1),
  ('Retail & Local Stores', 'seasonality', '🛍️ Hot Sale / Cyber Monday', 2),
  ('E-commerce / Online Stores', 'seasonality', '🛍️ Hot Sale / Cyber Monday', 0),
  ('E-commerce / Online Stores', 'seasonality', '🎄 Navidad y Fin de Año', 1),
  ('E-commerce / Online Stores', 'seasonality', '🎒 Vuelta a clases', 2),
  ('Fashion & Accessories', 'seasonality', '🌸 Primavera / Verano', 0),
  ('Fashion & Accessories', 'seasonality', '❄️ Otoño / Invierno', 1),
  ('Fashion & Accessories', 'seasonality', '🎄 Navidad y Fin de Año', 2),
  ('Education & Training', 'seasonality', '🎒 Vuelta a clases', 0),
  ('Education & Training', 'seasonality', '🎓 Fin de cursada', 1),
  ('Education & Training', 'seasonality', '🏖️ Vacaciones de verano', 2),
  ('Real Estate', 'seasonality', '🎒 Vuelta a clases (mudanzas)', 0),
  ('Real Estate', 'seasonality', '☀️ Verano', 1),
  ('Real Estate', 'seasonality', '🎄 Fin de año', 2),
  ('Professional Services', 'seasonality', '🎯 Enero (planificación anual)', 0),
  ('Professional Services', 'seasonality', '🎄 Cierre de año fiscal', 1),
  ('Marketing & Advertising Services', 'seasonality', '🎯 Enero (planificación anual)', 0),
  ('Marketing & Advertising Services', 'seasonality', '🎄 Cierre de año fiscal', 1),
  ('Construction & Home Renovation', 'seasonality', '☀️ Verano (obras)', 0),
  ('Construction & Home Renovation', 'seasonality', '🎒 Antes de vuelta a clases (remodelaciones)', 1),
  ('Tech & Software Startups', 'seasonality', '🎯 Enero (planificación anual)', 0),
  ('Tech & Software Startups', 'seasonality', '🎄 Cierre de año fiscal', 1),
  ('Creative Services', 'seasonality', '🎨 Verano (campañas)', 0),
  ('Creative Services', 'seasonality', '🎄 Cierre de año fiscal', 1),
  ('Travel, Tourism & Hospitality', 'seasonality', '☀️ Verano', 0),
  ('Travel, Tourism & Hospitality', 'seasonality', '🏖️ Vacaciones de invierno', 1),
  ('Travel, Tourism & Hospitality', 'seasonality', '✈️ Fechas turísticas', 2),
  ('Events & Entertainment', 'seasonality', '🎉 Fiestas de fin de año', 0),
  ('Events & Entertainment', 'seasonality', '💍 Temporada de casamientos', 1),
  ('Events & Entertainment', 'seasonality', '🎓 Egresados', 2),
  ('Automotive Services', 'seasonality', '☀️ Verano (viajes)', 0),
  ('Automotive Services', 'seasonality', '❄️ Invierno (mantenimiento)', 1),
  ('Financial Services', 'seasonality', '🎯 Enero (planificación financiera)', 0),
  ('Financial Services', 'seasonality', '📊 Cierre de ejercicio fiscal', 1),
  ('Home Services', 'seasonality', '🎒 Vuelta a clases (mudanzas)', 0),
  ('Home Services', 'seasonality', '☀️ Verano', 1),
  ('Home Services', 'seasonality', '🎄 Fin de año (limpieza)', 2),
  ('Manufacturing & Artisanal Production', 'seasonality', '🎄 Navidad y Fin de Año', 0),
  ('Manufacturing & Artisanal Production', 'seasonality', '🎒 Vuelta a clases', 1),
  ('Nonprofits & Social Causes', 'seasonality', '🎗️ Fin de año (campañas de donación)', 0),
  ('Nonprofits & Social Causes', 'seasonality', '🎄 Navidad solidaria', 1),
  ('Pet Services & Products', 'seasonality', '☀️ Verano', 0),
  ('Pet Services & Products', 'seasonality', '🎄 Navidad y Fin de Año', 1),
  ('Arts & Crafts', 'seasonality', '🎄 Navidad y Fin de Año', 0),
  ('Arts & Crafts', 'seasonality', '🎒 Vuelta a clases', 1),
  ('Business Consulting & Coaching', 'seasonality', '🎯 Enero (planificación anual)', 0),
  ('Business Consulting & Coaching', 'seasonality', '🎄 Cierre de año fiscal', 1),
  ('Agriculture & Natural Products', 'seasonality', '🌾 Cosecha', 0),
  ('Agriculture & Natural Products', 'seasonality', '☀️ Verano', 1),
  ('Food & Beverage', 'special_date', '☕ Día del Café', 0),
  ('Food & Beverage', 'special_date', '🍕 Día de la Pizza', 1),
  ('Food & Beverage', 'special_date', '🍞 Día del Panadero', 2),
  ('Beauty & Personal Care', 'special_date', '💅 Día de la Mujer', 0),
  ('Beauty & Personal Care', 'special_date', '💇 Día del Peluquero/a', 1),
  ('Health & Wellness', 'special_date', '🥗 Día Mundial de la Nutrición', 0),
  ('Health & Wellness', 'special_date', '🏃 Día Mundial de la Actividad Física', 1),
  ('Sports & Fitness', 'special_date', '🏃 Día Mundial de la Actividad Física', 0),
  ('Sports & Fitness', 'special_date', '⚽ Día del Deporte', 1),
  ('Retail & Local Stores', 'special_date', '🛍️ Black Friday', 0),
  ('Retail & Local Stores', 'special_date', '💻 Cyber Monday', 1),
  ('E-commerce / Online Stores', 'special_date', '🛍️ Black Friday', 0),
  ('E-commerce / Online Stores', 'special_date', '💻 Cyber Monday', 1),
  ('Fashion & Accessories', 'special_date', '👗 Semana de la Moda', 0),
  ('Fashion & Accessories', 'special_date', '🛍️ Black Friday', 1),
  ('Education & Training', 'special_date', '📚 Día del Estudiante', 0),
  ('Education & Training', 'special_date', '🍎 Día del Maestro', 1),
  ('Real Estate', 'special_date', '🏠 Día del Arquitecto', 0),
  ('Real Estate', 'special_date', '🔑 Día de la Vivienda', 1),
  ('Professional Services', 'special_date', '💼 Día del Emprendedor', 0),
  ('Professional Services', 'special_date', '🤝 Día de la Pyme', 1),
  ('Marketing & Advertising Services', 'special_date', '📱 Día del Community Manager', 0),
  ('Marketing & Advertising Services', 'special_date', '💡 Día de la Publicidad', 1),
  ('Construction & Home Renovation', 'special_date', '🏗️ Día del Arquitecto', 0),
  ('Construction & Home Renovation', 'special_date', '🔨 Día de la Construcción', 1),
  ('Tech & Software Startups', 'special_date', '💻 Día del Programador', 0),
  ('Tech & Software Startups', 'special_date', '🚀 Día del Emprendedor', 1),
  ('Creative Services', 'special_date', '🎨 Día del Diseñador Gráfico', 0),
  ('Creative Services', 'special_date', '📷 Día de la Fotografía', 1),
  ('Travel, Tourism & Hospitality', 'special_date', '🌍 Día Mundial del Turismo', 0),
  ('Travel, Tourism & Hospitality', 'special_date', '✈️ Día del Turista', 1),
  ('Events & Entertainment', 'special_date', '🎭 Día del Actor', 0),
  ('Events & Entertainment', 'special_date', '🎶 Día de la Música', 1),
  ('Automotive Services', 'special_date', '🚗 Día del Automovilista', 0),
  ('Automotive Services', 'special_date', '🔧 Día del Mecánico', 1),
  ('Financial Services', 'special_date', '💰 Día del Contador', 0),
  ('Financial Services', 'special_date', '📈 Día del Inversor', 1),
  ('Home Services', 'special_date', '🧹 Día del Trabajador de la Limpieza', 0),
  ('Home Services', 'special_date', '🔧 Día del Plomero', 1),
  ('Manufacturing & Artisanal Production', 'special_date', '🛠️ Día del Trabajador Industrial', 0),
  ('Manufacturing & Artisanal Production', 'special_date', '✋ Día del Artesano', 1),
  ('Nonprofits & Social Causes', 'special_date', '🤲 Día de la Solidaridad', 0),
  ('Nonprofits & Social Causes', 'special_date', '🌍 Día del Voluntariado', 1),
  ('Pet Services & Products', 'special_date', '🐾 Día del Animal', 0),
  ('Pet Services & Products', 'special_date', '🐶 Día del Veterinario', 1),
  ('Arts & Crafts', 'special_date', '✋ Día del Artesano', 0),
  ('Arts & Crafts', 'special_date', '🎨 Día del Arte', 1),
  ('Business Consulting & Coaching', 'special_date', '💼 Día del Emprendedor', 0),
  ('Business Consulting & Coaching', 'special_date', '🤝 Día de la Pyme', 1),
  ('Agriculture & Natural Products', 'special_date', '🌾 Día del Productor Agropecuario', 0),
  ('Agriculture & Natural Products', 'special_date', '🌱 Día de la Tierra', 1);
